# Generated by Django 3.2.5 on 2021-07-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imagedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Image File Name', max_length=70)),
                ('object_name', models.CharField(help_text='Name of the Object', max_length=50)),
                ('xmin', models.IntegerField(help_text='Minimum X co-ordinate')),
                ('ymin', models.IntegerField(help_text='Minimum Y co-ordinate')),
                ('xmax', models.IntegerField(help_text='Maximum X co-ordinate')),
                ('ymax', models.IntegerField(help_text='Maximum Y co-ordinate')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp')),
            ],
        ),
    ]
