# Generated by Django 3.2.5 on 2021-07-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='timestamp',
            field=models.DateField(auto_now_add=True, help_text='Timestamp'),
        ),
    ]
